---
# Site settings
locale: "en-US"
title: "Dr. Muhammad Munsif"
name: "Dr. Muhammad Munsif"
description: "PhD Researcher in Computer Vision, Deep Learning & Materials Informatics at Sejong University"
url: "https://munsif200.github.io"
baseurl: ""
repository: "munsif200/munsif200.github.io"

# Theme (AcademicPages uses Minimal Mistakes)
remote_theme: "mmistakes/minimal-mistakes@4.26.2"
minimal_mistakes_skin: "default"

# Plugins (GitHub Pages–compatible)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-seo-tag
  - jemoji

# Markdown + Math
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  hard_wrap: false

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true

# Author (shown in sidebar when author_profile: true)
author:
  name: "Dr. Muhammad Munsif"
  avatar: "/assets/images/Munsif.jpg"
  bio: "PhD Researcher in Computer Vision & AI at Sejong University"
  location: "Seoul, South Korea"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:munsif3797@gmail.com"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=YJ5X6HYAAAAJ&hl=en&authuser=1"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/munsif200"
---
