# Configuration for Jekyll  
  # Website URL  
  url: "https://munsif200.github.io"  
  # Author details  
  author:  
    name: "Munsif M. Agen"  
    email: "munsif@unist.ac.kr"  
  # Other configurations...